### PR TITLE
ISV sale options

### PR DESCRIPTION
**Pull request by jousis9**
I've added options to complete a sale if you have an ISV account.
They work ok as is, but since we just started integration I will continue to monitor and update if any bugs are found.

More info about the ISV partner program:
https://developer.vivawallet.com/isv-partner-program/

ISV options are shown here:
https://developer.vivawallet.com/apis-for-point-of-sale/card-terminal-apps/android-app/sale/

### CODE REVIEW

**Comment by drigler** [comment]
Hi, thanks. I'm not an ISV partner, so I didn't implemented it. This should be fine. Please test it and let me know if it works ok, so I can merge it to main.

Anyway, this plugin works for a 1,5 years on a various phones without a problem so far. Probably should remove the beta and update descriptions.

Thanks again.

Denis

**Comment by jousis9** [comment]
I had 0 issues with the plugin, it worked out of the box with our account.
Excellent work 👍 

We'll do much more tests with the ISV options next month and report back for the merge.

**Comment by drigler** [comment]
Hi, did you have a chance to test the plugin with ISV options added so I can merge your changes?

**Comment by jousis9** [comment]
We just got back from an expo where I had the code running on a demo account.
I need 2-3 days to look at the isv panel logs and will get back to you.

As far as I know, nobody had any apparent issue!

**Comment by drigler** [comment]
Cool, great. Let me know then...

btw where was the expo?

**Comment by jousis9** [comment]
https://horecaexpo.gr/en/

**Comment by drigler** [comment]
Superb

And what is your product? I'm just curious ;) You can mail me to drigler75@gmail.com

**Comment by jousis9** [comment]
I made a new function, isvSale, separate from the old sale to avoid any confusion with the nullable fields.
Tested them both with my ISV connected merchant account and both work ok, isvSale passes the isvAmount to the ISV account.

All ISV charges were processed correctly during my tests, so I think we are safe to merge.


For anyone interested, the following example request:
```dart
      final response = await pos.isvSale(
        amount: 10.0,
        tipAmount: 0.2,
        isvAmount: 0.1,
        clientTransactionId: 'CLIENT_TRANS_ID',
        isvClientId: 'ISV_CLIENT_ID',
        isvClientSecret: 'ISV_CLIENT_SECRET',
        isvMerchantId: 'ISV_MERCHANT_ID',
        isvClientTransactionId: 'ISV_CLIENT_TRANS_ID',
      );
```

will show up in your ISV account logs with 0.10euro on the ISV Amount column.

Notes
- isvCurrencyCode is required and set by default as Euro (978), please change it if you are not using Euro (See ISO4217).
- isvSourceCode is set as 'Default', if needed, please setup yours from: Sales > Physical Payments > Stores

New isvSale function requires an ISV multi merchant account, you cannot use it with your normal account.

**Comment by drigler** [comment]
Great job. New function is really better option because of all that ISV params.
I will make a quick check / test later and then merge your changes.

**Comment by drigler** [comment]
Everything is good, merged your changes. Also, the new package is published on pub.dev

Thanks for your contribution.

Cheers.

**Comment by abhishekSingh2735** [comment]
Thank you for providing this excellent package. However, could you please confirm if iOS support will be available in future updates?

**Comment by drigler** [comment]
Hi, unfortunately there is no planned support for IOS. I'am Android developer only. If anyone is willing to contribute to IOS support, I will be happy to publish the updated package.

**Pull request merged**
